CREATE TABLE [hosts] ([id] INTEGER NOT NULL UNIQUE,
[hostname] TEXT NOT NULL UNIQUE,
[ipaddress] TEXT NOT NULL UNIQUE,
[variables] TEXT,
PRIMARY KEY(id)
);

CREATE TABLE [playbooks] ([id] INTEGER NOT NULL UNIQUE,
[name] TEXT NOT NULL,
[path] TEXT NOT NULL UNIQUE,
PRIMARY KEY(id)
);

CREATE TABLE [playhistory] ([id] INTEGER NOT NULL UNIQUE,
[hostid] INTEGER NOT NULL,
[playbookid] INTEGER NOT NULL,
[date] DATETIME NOT NULL,
[ok] INTEGER NOT NULL DEFAULT '0',
[changed] INTEGER NOT NULL DEFAULT '0',
[unreachable] INTEGER NOT NULL DEFAULT '0',
[failed] INTEGER NOT NULL DEFAULT '0',
PRIMARY KEY(id)
);